ALTER TABLE users ADD COLUMN IF NOT EXISTS birthdate DATE;
ALTER TABLE users ADD COLUMN IF NOT EXISTS work_direction VARCHAR(300);
ALTER TABLE users ADD COLUMN IF NOT EXISTS organization VARCHAR(300);